### ISSUE TITLE
Full recording of an object

### ISSUE THREAD

**Issue by brianwgoldman** [mlcommons/newhelm#127]
Something messy that has cropped up in parameterized objects (SUTs, Tests, a few others), is that to really reproduce what they did from a record, we need to know what parameters were passed into them. Specifically:

* It is insufficient to know you used the `BBQ` Test, if we don't know how the `subject` argument was set.
* Knowing you used `TogetherChatSUT` could be one of eight different SUTs.

There are two current solutions in NewHELM, both kind of suck:
1. [PR 119](https://github.com/mlcommons/newhelm/pull/119) lets whoever calls the runner assign arbitrary names to all the objects, so you can use whatever code that performed the run to track back to the arguments.
2. InstanceFactories allow for storing the name + args for an object. We can write down the registry and the keys used, but we don't currently require runner to use them at all.

Old HELM kinda solves this problem with [parse_object_spec](https://github.com/stanford-crfm/helm/blob/98d6f18af6c7697cb0f12ded249a7343a72b2843/src/helm/common/object_spec.py#L89), which converts the class+init parameters into a string.

This issue is to come up with a good solution.

**Comment by wpietri** [comment]
Agreed we need to fix this. My concern with arbitrary names is that they probably shouldn't be arbitrary, in the sense that calling tests things like `joe` and `bob` or `1`, `2`, and `3` will be bad from the perspective of a person (or code) trying to look at test records and understand what happened. The names should instead be meaningful, and that meaning will be pretty close to things that Test and SUT objects get handed at some point or another.

To me that suggests we want something relatively standard and easy, along the lines of  `repr` with good defaults in the base object. Given that this is for a relatively small number of long-lived objects, perhaps we could use the `inspect` module to provide a good automated default?

**Comment by brianwgoldman** [comment]
We have a "good enough for now" solution in #137 and #138.
