### ISSUE TITLE
TogetherAI rate limits should not crash app

### ISSUE THREAD

**Issue by wpietri** [mlcommons/newhelm#166]

**Comment by mkly** [comment]
In the short term:
https://github.com/mlcommons/newhelm/pull/161

**Comment by wpietri** [comment]
Ah, great. Ships passing in the night, etc. Is this already released? I'm not sure what our release approach is. Something we should discuss tomorrow, I imagine.

**Comment by ashahba** [comment]
This is now with tip of `main` at `f71c781`:
![commit_f71c781](https://github.com/mlcommons/newhelm/assets/12436063/85b43eb5-6e34-49a1-92ce-c9570e0c8e1e)

**Comment by brianwgoldman** [comment]
I think #194 has a solution to this issue.

**Comment by ashahba** [comment]
I also verified that with a free account, the highest `--max-test-items` I can get this test to pass is `2` and if fails with `3` and up:
```
$ poetry run python newhelm/main.py run-test --sut demo_yes_no --max-test-items 2 --test simple_safety_tests
```

**Comment by brianwgoldman** [comment]
I don't think we've had any issues since #194 merged, so closing as fixed. If these resurface please reopen this bug.
