### ISSUE TITLE
Empty comments should not crash Perspective annotator

### ISSUE THREAD

**Issue by wpietri** [mlcommons/newhelm#167]

**Comment by brianwgoldman** [comment]
Can you provide some details on how you got in this situation? It seems wrong that a SUT should return zero text for a prompt.

**Comment by brianwgoldman** [comment]
It looks like HELM handles this by [dropping the empty completions](https://github.com/stanford-crfm/helm/blob/5f674f82211fcf07d2c093bfd876b27315438c16/src/helm/benchmark/metrics/toxicity_metrics.py#L56-L57) before sending to PerspectiveAPI.

I think we should make sure the [completions list in the Annotation](https://github.com/mlcommons/newhelm/blob/a796c7dc04aa3adaa64d1939a11edf8e5a737829/plugins/perspective_api/newhelm/annotators/perspective_api.py#L32) stays aligned with completions in the SUTResponse. I think the best option would be to populate `scores` with zeros for the requested attributes.

**Comment by brianwgoldman** [comment]
Fixed in #184.
